In [1]:
a = [10,243,53,65465,43]
b = [32,56,34,56,345]
a-b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [3]:
import numpy as np

a = np.array([10,243,53,65465,43,45,678])
b = np.array([32,56,34,56,345])
a-b

ValueError: operands could not be broadcast together with shapes (7,) (5,) 

In [4]:
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [6]:
for col in b:
    for i in col:
        print(i)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [7]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [10]:
b[b>10]

array([11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40, 41, 42, 43])

In [13]:
rg = np.random.default_rng(1)
10*rg.random((2, 2))

array([[5.11821625, 9.50463696],
       [1.44159613, 9.48649447]])

In [14]:
a = np.floor(10 * rg.random((2, 12)))
a

array([[3., 4., 8., 4., 5., 0., 7., 5., 3., 7., 3., 4.],
       [1., 4., 2., 2., 7., 2., 4., 9., 9., 7., 5., 2.]])

In [15]:
b = np.hsplit(a, 3)
b

[array([[3., 4., 8., 4.],
        [1., 4., 2., 2.]]),
 array([[5., 0., 7., 5.],
        [7., 2., 4., 9.]]),
 array([[3., 7., 3., 4.],
        [9., 7., 5., 2.]])]

In [16]:
b[1]

array([[5., 0., 7., 5.],
       [7., 2., 4., 9.]])

In [17]:
np.array(b)

array([[[3., 4., 8., 4.],
        [1., 4., 2., 2.]],

       [[5., 0., 7., 5.],
        [7., 2., 4., 9.]],

       [[3., 7., 3., 4.],
        [9., 7., 5., 2.]]])

1) Создаете руками файл
2) Записываете руками числа, 1 на строку (> 10)
3) Считываете содержимое файла в список numpy, ndim = 2 (a)
4) Создаете 2 список из случайных чисел (b)
5) c = 10*b+b*a
6) Транспонируете c
7) Разбиваете a,b на 2 части по столбцам (a1,b1)
8) a1[0] соединяете по строкам с b[1] = a2,  b1[0] с a[1] = b2
9) a2 / (c.mean()*c.max()) = a3
10) Сохраняете c, a2,a3(только элементы >10) в файл, используя стандартные операции
